name: snake_chef
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flame: 0.19.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/floor.png
    - assets/images/ingredients.png
    - assets/images/plates.png
    - assets/images/snake.png
    - assets/images/buttons.png
    - assets/images/background_pattern.png
    - assets/images/title.png
    - assets/images/nine_box_tileset.png
    - assets/images/nine_box_white_tileset.png

    - assets/stages/0.json

    - assets/audio/gameover.wav
    - assets/audio/gameplay.mp3
    - assets/audio/title.wav
    - assets/audio/win_fanfarre.wav
    - assets/audio/ingredient_collected.wav
    - assets/audio/recipe_done.wav

  fonts:
   - family: VictorPixel
     fonts:
       - asset: assets/fonts/victor-pixel.ttf
