name: snake_chef
description: Snake Chef

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flame:
    git:
      url: git@github.com:tyemy/flame.git
      ref: develop
  flame_splash_screen: 0.0.1
  flame_fire_atlas:
    git:
      url: git@github.com:tyemy/fire-atlas.git
      ref: snake-chef/test
      path: flame_fire_atlas
  ocarina: ^0.0.2
  shared_preferences: 0.5.7
  url_launcher: 5.4.7
  flutter_vibrate: 1.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "assets/icon/icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/fireslime-banner.png

    - assets/images/floor.png
    - assets/images/snake.png
    - assets/images/buttons.png
    - assets/images/pattern.png
    - assets/images/title.png
    - assets/images/nine_box_tileset.png
    - assets/images/nine_box_white_tileset.png

    - assets/images/gamepad_tutorial.png
    - assets/images/touch_tutorial.png

    - assets/stages/
    - assets/recipes/

    - assets/audio/gameover.aac
    - assets/audio/gameplay.wav
    - assets/audio/title.wav
    - assets/audio/win_fanfarre.aac

    - assets/audio/ingredient_collected.wav
    - assets/audio/recipe_done.wav

    - assets/atlases/ingredients.fa
    - assets/atlases/plates.fa
    - assets/atlases/slider.fa

  fonts:
    - family: VictorPixel
      fonts:
        - asset: assets/fonts/victor-pixel.ttf
